#!/usr/bin/env python  
# -*- coding:utf-8 -*-  
  
# API key：273646050  
# keyfrom：11pegasus11  
  
import json  
import sys  
  
try:    # py3  
    from urllib.parse import urlparse, quote, urlencode, unquote  
    from urllib.request import urlopen  
except:    # py2  
    from urllib import urlencode, quote, unquote  
    from urllib2 import urlopen  
  
  
def fetch(file,query_str=''):  
    query_str = query_str.strip("'").strip('"').strip()  
    if not query_str:  
        query_str = 'python'  
  
    print(query_str)  
    file.write('%s,'%(query_str))
    query = {  
        'q': query_str  
    }  
    url = 'http://fanyi.youdao.com/openapi.do?keyfrom=11pegasus11&key=273646050&type=data&doctype=json&version=1.1&' + urlencode(query)  
    response = urlopen(url, timeout=3)  
    html = response.read().decode('utf-8')  
    return html 
  
  
def parse(html,file):  
    d = json.loads(html)  
    try:  
        if d.get('errorCode') == 0:     
            explains = d.get('basic').get('explains')  
            for i in explains:  
                print(i)  
                file.write('%s'%i)
            file.write('\n')
        else:  
            print('无法翻译')  
  
    except:  
        print('翻译出错，请输入合法单词')  
  
  
def main():  
    try:  
        s = sys.argv[1]  
    except IndexError:  
        s = 'python' 
    ###change this dictionary '/home/wang/my_cloud/' is where you save the notebook
    with open('/home/wang/my_cloud/wordnote.csv','a') as f: 
    ###change this dictionary 'wordnote' is the name of your notebook
        parse(fetch(f,s),f)  
  
  
if __name__ == '__main__':  
    main()  